version: '3'
services:
  db:
    image: postgres
    restart: unless-stopped
    env_file:
      - db.env
    volumes:
      - db:/var/lib/postgres/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    depends_on:
      db:
        condition: service_healthy
    build: .
    restart: unless-stopped
    ports:
      - 13000:3000
    env_file:
      - .env
volumes:
  db: